enum PersonTypeAttention {
    TRABAJADOR = 'TRABAJADOR',
    PATRONO = 'PATRONO',
    REPRESENTANTE_LEGAL = 'REPRESENTANTE_LEGAL',
    APODERADO_LEGAL = 'APODERADO_LEGAL',
    SINDICATO = 'SINDICATO'
  }
  export default PersonTypeAttention;